# Generated by Django 2.0 on 2019-07-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viatimin',
            new_name='Vitamin',
        ),
    ]
